openapi: 3.2.0
info:
  title: Criteo Creative API
  description: Criteo API - MarketingSolutions
  version: 2026-07
servers:
- url: https://api.criteo.com
security:
- oauth: []
tags:
- name: Creative
paths:
  /2026-07/marketing-solutions/ads/{id}:
    delete:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/ads/{id}
      description: Delete an Ad
      operationId: DeleteAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/ads/{id}
      description: Get an Ad with its id
      operationId: GetAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/ads:
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/ads
      description: Get the list of self-services Ads for a given advertiser
      operationId: GetAdvertiserAds
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
    post:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/ads
      description: Create an Ad
      operationId: CreateAdvertiserAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons:
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons
      description: Get the list of self-services Coupons for a given advertiser
      operationId: GetAdvertiserCoupons
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
    post:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons
      description: Create a Coupon
      operationId: CreateAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons-supported-sizes:
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons-supported-sizes
      description: Get the list of Coupon supported sizes
      operationId: GetAdvertiserCouponSupportedSizes
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}:
    delete:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}
      description: Delete a Coupon
      operationId: DeleteAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}
      description: Get a Coupon with its id
      operationId: GetAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
    put:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}
      description: Edit a specific Coupon
      operationId: EditAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}/preview:
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}/preview
      description: Get the preview of a specific Coupon
      operationId: GetAdvertiserCouponPreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
  /2026-07/marketing-solutions/advertisers/{advertiser-id}/creatives:
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/creatives
      description: Get the list of self-services Creatives for a given advertiser
      operationId: GetAdvertiserCreatives
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
    post:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/advertisers/{advertiser-id}/creatives
      description: Create a Creative
      operationId: CreateAdvertiserCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
  /2026-07/marketing-solutions/creatives/{id}:
    delete:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/creatives/{id}
      description: Delete a Creative if there are no ads binded to it
      operationId: DeleteCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
    get:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/creatives/{id}
      description: Get a Creative with its id
      operationId: GetCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
    put:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/creatives/{id}
      description: Edit a specific Creative
      operationId: EditCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
  /2026-07/marketing-solutions/creatives/{id}/preview:
    post:
      tags:
      - Creative
      summary: /2026-07/marketing-solutions/creatives/{id}/preview
      description: Get the preview of a specific Creative
      operationId: GenerateCreativePreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby
