openapi: 3.2.0
info:
  title: Criteo Reco API
  description: Criteo API - MarketingSolutions
  version: 2026-07
servers:
- url: https://api.criteo.com
security:
- oauth: []
tags:
- name: Reco
paths:
  /2026-07/marketing-solutions/ads/{ad-id}/product-boost:
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-boost
      description: Fetch all boosting associations and configurations
      operationId: FetchBoostedAdAssociations
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
  /2026-07/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}:
    delete:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}
      description: Delete association and configuration.
      operationId: DeleteBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}
      description: Fetch boosting association and configuration
      operationId: FetchBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
    post:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}
      description: Create or update product boosting configuration
      operationId: CreateBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
  /2026-07/marketing-solutions/ads/{ad-id}/product-filter:
    delete:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-filter
      description: Disable product filtering for a given ad
      operationId: DisableProductFiltering
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-filter
      description: Fetch product filtering configuration for a given ad
      operationId: FetchProductFilteringConfig
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
    post:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/ads/{ad-id}/product-filter
      description: Enable product filtering for a given ad
      operationId: EnableProductFiltering
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
  /2026-07/marketing-solutions/dataset/{dataset-id}/product-boost:
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/dataset/{dataset-id}/product-boost
      description: Fetch boosting association and configuration for a given partner
      operationId: FetchBoostedAdAssociationByPartnerId
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
  /2026-07/marketing-solutions/product-sets:
    post:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets
      description: Create a new product set
      operationId: CreateProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
  /2026-07/marketing-solutions/product-sets/{product-set-id}:
    delete:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets/{product-set-id}
      description: Remove a product set
      operationId: RemoveProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets/{product-set-id}
      description: Fetch an existing product set
      operationId: FetchProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
    patch:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets/{product-set-id}
      description: Patch an existing product set
      operationId: PatchProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
  /2026-07/marketing-solutions/product-sets/{product-set-id}/product-filters:
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets/{product-set-id}/product-filters
      description: Fetch product filtering usages for a given product set
      operationId: FetchProductFilteringUsages
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
  /2026-07/marketing-solutions/product-sets/dataset/{dataset-id}:
    get:
      tags:
      - Reco
      summary: /2026-07/marketing-solutions/product-sets/dataset/{dataset-id}
      description: Fetch product sets of a given dataset
      operationId: FetchProductSets
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby
